### ISSUE TITLE
Get WACZ user-agent

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/integrity-v2#13]
In the past this was done with the wacz Python library. I don't think they have a Go library, but this can be done by looking at one of the WARC files inside the WACZ, and walking through the lines until `User-Agent:` is found.

This is not our top priority currently.

**Comment by williamchong** [comment]
Where would we put the result? i.e. what should be the attribute key?

**Comment by makew0rld** [comment]
Let's go with `crawl_user_agent` for now.
