### ISSUE TITLE
asset_origin_type attribute

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/integrity-v2#24]
I think it would be useful to have an `asset_ingest_type` attribute that explains what kind of ingestion path this asset has been part of. Already in the codebase we are developing multiple paths that create different attributes. For example if an asset comes from a Proofmode ZIP, it will be processed differently and the `proofmode` attribute will exist. If it comes from a folder, it will have a `last_modified` attribute, etc.

`asset_ingest_type` allows us to know where the asset came from, how it was processed, and what attributes it likely has.

Values:
- `browsertrix`
- `folder`
- `proofmode`
- etc

**Comment by benhylau** [comment]
`asset_origin_type`?

**Comment by makew0rld** [comment]
See https://github.com/starlinglab/integrity-v2/issues/3#issuecomment-2160810593 for details/example

**Comment by makew0rld** [comment]
@williamchong please set this for regular files, to just `folder`
