### ISSUE TITLE
Allow-list of public keys

### ISSUE THREAD

**Issue by makew0rld** [starlinglab/integrity-v2#25]
Every time signatures are verified in the code (proofmode, wacz) the public key needs to first be checked against a list of known good public keys. Otherwise there is no point to verifying the signature.

Ben has said this list of good keys will be in the preproc database.

Metadata for these keys should also be stored and passed into AA. Could be something simple like just a name for each key, or something more complex like an author object.

If no keys are defined then all signature verifications MUST fail.

**Comment by makew0rld** [comment]
For Browsertrix WACZs, this should also include a allow-list for the `signedData.domain` field, as that is equivalent to the public key. It seems that list should only include `signing.app.browsertrix.com` for now. I can check with Illya to confirm no other domains will be used.

**Comment by benhylau** [comment]
This all sounds right. A new table in the preproc database that contains a `key + verification method -> author information` seems right.

If you are concerned about each preproc having its own database, perhaps we should have them all share one database for now?

**Comment by makew0rld** [comment]
- [ ] Document key type strings and formats
- [ ] Document how to add a key
