### ISSUE TITLE
Internal demo

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-v2#27]
1. Set up a project with ID `authattr-demo-2024-06` through database management interface

1. Send [Dropbox File Request](https://help.dropbox.com/share/create-file-request) to @walkerlj0 and she will upload a:
    - photo
    - video
    - audio
    - other arbitrary files
    - ProofMode bundles
    - Web archives (pre-created, cloud crawls are out of scope)

1. Have _everyone_ use CLI to look at open-access Authenticated Attributes Service. Verify each of the keys in https://github.com/starlinglab/integrity-v2/issues/3

1. @makew0rld to show encrypted attributes (where to find decryption key and what CLI command to use)

1. Show upload to w3s and Google Drive

1. Show registration to Numbers

1. Show export to VC

1. Show export to C2PA (include origin signature, w3s storage record, registration Tx to Numbers)

**Comment by makew0rld** [comment]
We will probably want to get indexing of filenames set up, and a CLI tool for searching the index. Otherwise step 3 will be tricky because it will require everyone to know the CIDs of the files Lindsay uploaded, or to have the files on hand to generate the CIDs themselves.

**Comment by makew0rld** [comment]
@williamchong can you add indexing for `file_name` and `asset_origin_id` by default for all preprocessors?

**Comment by williamchong** [comment]
> @williamchong can you add indexing for `file_name` and `asset_origin_id` by default for all preprocessors?

Please see if this approach works
https://github.com/starlinglab/integrity-v2/pull/35

**Comment by makew0rld** [comment]
@benhylau feel free to add Google Drive link to Zoom recording here

**Comment by makew0rld** [comment]
Demo recording: https://drive.google.com/file/d/1dJMZ_hLLM-L73LrLiS4A0nYKUBsWaip0/view?ts=667b6c51
