### ISSUE TITLE
Simple endpoint for browsertrix cloud webhook events

### ISSUE THREAD

**Issue by williamchong** [starlinglab/integrity-v2#33]
- setup webhook in app.browsertrix.com
- receive crawl complete event
- fetch crawl id to receive metadata like project id/etc
- download wacz bundle from crawl event data
- handle both wacz bundle and metadata like in folder preprocessor

**Comment by makew0rld** [comment]
Webhook docs: https://app.browsertrix.com/api/redoc

Webhook has to be set up through API of Browsertrix Cloud currently, it can't be configured in the web interface.
