### ISSUE TITLE
File encryption and secret attribute handling

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-v2#4]
TBD

**Comment by makew0rld** [comment]
From the [design doc](https://docs.google.com/document/d/13IY9Ca8tqy5XTlHSvUq1gfHQkB8oUcQBN22sSoU7kKo/edit):

> The [webhook] service will recognize which metadata fields contain private information, and tell AA to encrypt them with the key it provides. These keys will be stored in a common folder and named per-path, like “cms1-elections”. Each key is just a file containing 32 random bytes.

The design doc defines an "encryptor" CLI, so my thinking is that file encryption is handled at a later stage, not by the webhook. Files are stored (temporarily) un-encrypted on the filesystem always, and they can be encrypted and deleted manually later using the CLI.

**Comment by makew0rld** [comment]
This basically done, or covered by other issues. See #28 and #22 and #21
