### ISSUE TITLE
Handling of ProofMode and WACZ bundles

### ISSUE THREAD

**Issue by benhylau** [starlinglab/integrity-v2#7]

**Comment by makew0rld** [comment]
Our previous Python code for validating signatures is here: https://github.com/starlinglab/integrity-preprocessor/tree/main/lib/validate

**Comment by williamchong** [comment]
Do we want to send every key in the ProofMode metadata json onto aa?

**Comment by makew0rld** [comment]
Most likely, although some keys like location coordinates should probably be private by default. During your testing you can put the current Proofmode JSON here to show what it looks like.

**Comment by williamchong** [comment]
From my android phone, without giving GPS permission

```{
  "File Hash SHA256": "4bc14bc3f2f22d84d854309725ead5c175e1fd9b13d8a91ea9714ea18dfecdc4",
  "Locale": "HKG",
  "SafetyCheckCtsMatch": "",
  "Location.Provider": "none",
  "Location.Longitude": "",
  "Location.Accuracy": "",
  "Location.Bearing": "",
  "File Created": "2024-05-27T00:48:28.000Z",
  "SafetyCheckBasicIntegrity": "",
  "Location.Time": "",
  "File Modified": "2024-05-27T00:48:28.148Z",
  "Location.Latitude": "",
  "Language": "中文",
  "SafetyCheck": "false",
  "Location.Altitude": "",
  "SafetyCheckTimestamp": "",
  "Proof Generated": "2024-05-27T00:48:32.172Z",
  "Manufacturer": "samsung",
  "Hardware": "Samsung SM-S9110",
  "File Path": "\/storage\/emulated\/0\/DCIM\/ProofMode\/1716742106663.jpg",
  "ScreenSize": "5.791836340451971",
  "Location.Speed": "",
  "Notes": "ProofMode v2.3.0-RC-1 autogenerated=false"
}```

**Comment by makew0rld** [comment]
Thanks. There's two ways of adding this (after removing private keys like location). One is just one field called `proofmode_metadata` with all the keys under it. Or to add each key individually.

The latter seems nicer, but we run the risk of some semantic confusion, for example to someone looking at it later, it will be confusing what the difference between `sha256` and `File Hash SHA256` is, or `file_path` and `File Path`.

We will have to discuss this.

**Comment by williamchong** [comment]
For `wacz`, what should be the asset that are to be uploaded? `data.warc.gz` ?

**Comment by makew0rld** [comment]
Under the key `proofmode`:
```json
{
  "metadata": "<string of proof.json>"
  "meta_sig": "<string of proof.json signature>"
  "media_sig": "<string of .asc>"
  "pubkey": "<string of pubkey.asc>"
  "ots": "<bytes of .ots>"
  "gst": "<string of .gst>"
}
```

Some of the fields from the metadata can be extracted, renamed, and promoted to top-level.

**Comment by makew0rld** [comment]
#20 should close this? Not sure if there's anything left to be done for this issue after that.

**Comment by williamchong** [comment]
> #20 should close this? Not sure if there's anything left to be done for this issue after that.

Yes it should

**Comment by makew0rld** [comment]
Final feature of WACZ processing and verification was completed in #20 :tada:
